tasks:
  - init: |
      pip3 install -r requirements.txt
      cd `python -m site --user-site`   
      curl -sS https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-37-v0.6.0-e44221c-linux64.zip > file.zip 
      unzip file.zip                                  
      rm file.zip
  
  - init: | 
      cd /workspace
      git clone https://github.com/openai/gym 
      cd gym
      pip install -e .
      cd ..
    command: |
      cd /workspace/factorySim
      pip3 install setup.py -e .

vscode:
  extensions:
    - daylerees.rainglow@1.5.2:CMeB8a/apImXE9fKgInsdQ==
