tasks:
  - init: pip3 install -r requirements.txt
    command: bash downloadIFCOpenShell.sh
  - init: git clone https://github.com/openai/gym 
    command: cd gym
    command: pip install -e

   # command: echo "Replace me with omething that should run on every start, or just
    #  remove me entirely."

vscode:
  extensions:
    - daylerees.rainglow@1.5.2:CMeB8a/apImXE9fKgInsdQ==